# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: YumaWay CI/CD

on:
  schedule:
    - cron: '0 0 * * 4'

  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 15.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install npm dependencies    
      run: npm ci
    - name: Run Build
      run: npm run build 
    - name: Deploy Build to Dev Server
      uses: easingthemes/ssh-deploy@main
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.SSH_YUMA_SECRET }}
        SOURCE: "client/build"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "/var/www/yumaway.com/"
    
